# Generated by Django 4.1.1 on 2022-09-05 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=255)),
                ('author', models.TextField(max_length=255)),
                ('genre', models.TextField(max_length=100)),
            ],
        ),
    ]
